name: Code Review
on:
  - pull_request
  - pull_request_review
  - pull_request_review_comment

jobs:
  build:
    name: Danger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: danger/danger-js@9.1.8
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DANGER_DISABLE_TRANSPILATION: "true"